apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        ports:
        - name: entrypoint
          containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: 5432
    targetPort: entrypoint
    name: entrypoint
  selector:
    app: postgres