kind: pipeline
type: docker
name: build_image

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - dev

steps:
  - name: Get git commit tag
    image: alpine
    commands:
      - apk add git
      - git rev-parse --short HEAD > .tags
      - cat .tags
  - name: Build and push
    image: plugins/docker
    settings:
      dockerfile: apps/backend/Dockerfile
      registry: git.odzi.dog
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
      repo: git.odzi.dog/snacktime/backend

---
kind: pipeline
type: docker
name: deploy_dev

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - dev

steps:
  - name: Trigger snacktime/dev.snacktime.recipes pipeline
    image: plugins/downstream
    settings:
      server: https://drone.odzi.dog
      token:
        from_secret: DRONE_TOKEN
      fork: true
      repositories:
        - snacktime/dev.snacktime.recipes

depends_on:
  - build_image
