tag: "cc6f736"

volumes:
  storageClass: "openebs-hostpath"

# -------------------------------------
# Backend
backend:
  image: git.odzi.dog/snacktime/backend
  replicaCount: 1

# -------------------------------------
# Postgres
postgres:
  image: postgres
  tag: "15.2"