tag: "b15aaa6"

volumes:
  storageClass: "openebs-hostpath"

# -------------------------------------
# Secret and internal keys
secrets:
  appKey: ""
  internalKeys:
  - ""

# -------------------------------------
# Backend
backend:
  image: git.odzi.dog/snacktime/backend
  replicaCount: 1

  ingress:
    url: "api.dev.snacktime.recipes"

# -------------------------------------
# Web
web:
  image: git.odzi.dog/snacktime/web
  ingress:
    url: "dev.snacktime.recipes"

# -------------------------------------
# Postgres
postgres:
  image: postgres
  tag: "15.2"