apiVersion: apps/v1
kind: Deployment
metadata:
  name: snacktime
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: snacktime-backend
  replicas: {{ default 1 .Values.backend.replicaCount | int }}
  template:
    metadata:
      labels:
        app: snacktime-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "3333"
        - name: HOST
          value: "0.0.0.0"
        - name: NODE_ENV
          value: production
        
        - name: APP_KEY
          value: "Y48GY8QSHbGFjuUiyXdMGELJf-wShDXO"
        - name: DRIVE_DISK
          value: "local"
        
        - name: DB_CONNECTION
          value: "pg"
        - name: PG_HOST
          value: "postgres"
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          value: "postgres"
        - name: PG_PASSWORD
          value: "postgres"
        - name: PG_DB_NAME
          value: "postgres"
        ports:
        - name: entrypoint 
          containerPort: 3333