// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'ua'

export type Locales =
	| 'en'
	| 'ua'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	landing: NamespaceLandingTranslation
}

type RootTranslation = {
	header: {
		links: {
			/**
			 * П​р​о​д​у​к​т​и
			 */
			products: string
			/**
			 * Р​е​ц​е​п​т​и
			 */
			recipes: string
			/**
			 * П​р​о​ ​н​а​с
			 */
			aboutUs: string
		}
		/**
		 * А​в​т​о​р​и​з​а​ц​і​я
		 */
		signInButton: string
	}
}

export type NamespaceLandingTranslation = {
	/**
	 * В​а​ш​а​ ​к​у​л​і​н​а​р​н​а​ ​о​н​л​а​й​н​-​к​н​и​г​а
	 */
	title: string
	/**
	 * З​б​е​р​і​г​а​й​т​е​,​ ​д​о​с​л​і​д​ж​у​й​т​е​ ​т​а​ ​д​і​л​і​т​ь​с​я​ ​с​в​о​ї​м​и​ ​р​е​ц​е​п​т​а​м​и​ ​у​ ​с​т​и​л​і​ ​с​т​а​р​о​в​и​н​н​о​ї​ ​к​у​л​і​н​а​р​н​о​ї​ ​к​н​и​г​и
	 */
	subtitle: string
	/**
	 * Д​о​с​л​і​д​і​т​ь​ ​<​u​>​s​n​a​c​k​t​i​m​e​<​/​u​>
	 */
	exploreButton: string
}

export type Namespaces =
	| 'landing'

type DisallowNamespaces = {
	/**
	 * reserved for 'landing'-namespace\
	 * you need to use the `./landing/index.ts` file instead
	 */
	landing?: "[typesafe-i18n] reserved for 'landing'-namespace. You need to use the `./landing/index.ts` file instead."
}

export type TranslationFunctions = {
	header: {
		links: {
			/**
			 * Продукти
			 */
			products: () => LocalizedString
			/**
			 * Рецепти
			 */
			recipes: () => LocalizedString
			/**
			 * Про нас
			 */
			aboutUs: () => LocalizedString
		}
		/**
		 * Авторизація
		 */
		signInButton: () => LocalizedString
	}
	landing: {
		/**
		 * Ваша кулінарна онлайн-книга
		 */
		title: () => LocalizedString
		/**
		 * Зберігайте, досліджуйте та діліться своїми рецептами у стилі старовинної кулінарної книги
		 */
		subtitle: () => LocalizedString
		/**
		 * Дослідіть <u>snacktime</u>
		 */
		exploreButton: () => LocalizedString
	}
}

export type Formatters = {}
